[metadata]
name = cocotbext-spi
description = SPI modules for cocotb
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
author = Spencer Chang
author_email = spencer@sycee.xyz
classifiers =
    Development Status :: 3 - Alpha
    Programming Language :: Python :: 3
    Operating System :: OS Independent
    Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)
project_urls =
    repository = https://github.com/schang412/cocotbext-spi

[options]
packages = find_namespace:
python_requires = >=3.9
install_requires =
    cocotb>=2.0.0
include_package_data = True

[options.packages.find]
include =
    cocotbext.*

[options.extras_require]
dev =
    cocotb-test>=0.2.6
    pytest>=8.3.5
    pytest-xdist>=3.6.1
    tox>=4.25.0
lint =
    flake8>=7.3.0

[tool:pytest]
testpaths =
    tests
addopts = --import-mode importlib

[setuptools_scm]
write_to = cocotbext/spi/_version.py
