name: Regression Tests

# Run this workflow every time a new commit pushed to an open PR, or manually
on:
  # Caution: Not sensitive to edited, because running on changed comments is pointless almost always.defaults:
  # The exceptions is if changing base branch. If that occurs, a manual run is probably in order
  pull_request:
    types: [opened, reopened, edited, synchronize]

  # CI can be manually started on any branch
  workflow_dispatch:

# This sets up a concurrency group for the branch associated with the workflow.defaults:
# If a new workflow is triggered, any running workflow with the same concurrency group will be cancelled.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# These are keys for gcs access. But nix is looking for s3 compatibility, so we expose via AWS env variables
env:
  USER: runner
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    name: Python ${{matrix.python-version}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}

    - name: Install Icarus Verilog
      run: |
        sudo apt install -y --no-install-recommends iverilog
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox

  publish_pypi:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        with:
          python-version: '3.10'
        uses: actions/setup-python@v4
      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv publish
      - name: Create Release on Github
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          files: ./dist/*
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
